language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'

script:
- npm run lint
- npm run build
- npm run test:coverage
- npm run docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: iPWbnDqYXWm+YZpx0wQlUNZXwnPyxg7N6ARB/u862E34PH++zU9tKLLUDMTxBQoF1qGigiESNRwohyi8ToZJSTQnlpSwKl5QRWpVvCDY1AfuNsBTfVd0ZQxB027HlHq0SBvvHXmA/+jJgSg0Zx+L8yShXhqbsSjhqqMef61fM0faDIOZ0mrmSAQKVWAhPoPkRZj0RqazePDWDFDr/EcxXmMSGQs4/I59d63t8iZatawg65ej8mw79vHSFtNpKARVCtw3qD6yRz0WtabxXkLb49mAt0aWqBkLmpEAG7YhtYS/MYH2XagbfuNVi952IftlctM+Sda6cxNvugkRO4sKw0p2FR7ST2AIaEQ6AmOm7U5EKMwG3VqHsf525eS5pbj7ciSKEfd28gOY4ybYoegjHYbL+csUkFCsoM/C3R5/a15x7JFElOpgLrhg0BsveTzYbUqIM9AHhVN/6EyctASFYYCJGFzZ0n5i3/zfba5SmWySvksaw3gYEzzpl/eTVFBT5VmEBIL1NBRwPvuNdwtxlxr/DgaKRDVuff0ZLzkKZNHSf2RutAR6/+oDeKohaUwqN6hudaseDJZABKLKpTJjbgUQ2180muMaatdqjRuVFS2RUHKwO4Cm8tDJ42I1VXSedVaugIiQcsVykKSzV+MrzzsoanmTIDQGmcp+6hDFCMI=
  keep-history: true
  local-dir: ./docs
  verbose: true
  on:
    branch: master
